kickfarter/app/urls.py
import app.views
from django.conf.urls import url
from django.conf.urls.static import static
from kickfarter import settings

urlpatterns = [
    url(r'^$', app.views.index, name='index'),
    url(r'^login$', app.views.login_view, name='login'),
    url(r'^logout', app.views.logout_view, name='logout'),
    url(r'^signup$', app.views.signup, name='signup'),
    url(r'^profile$', app.views.profile, name='profile'),
    url(r'^start$', app.views.start_project, name='start_project'),
    url(r'^discover$', app.views.discover, name='discover'),
    url(r'^project/(?P<id>\d+)/edit$', app.views.edit_project, name='edit_project'),
    url(r'^project/(?P<id>\d+)$', app.views.view_project, name='view_project'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kickfarter/kickfarter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

handler404 = 'app.views.error'

kickfarter/app/models.py
import datetime

from app.exceptions import BackingException
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import MinValueValidator
from django.db import models


class UserManager(BaseUserManager):
    """Boilerplate code because Django..."""
    def create_user(self, email, password, name=None):
        user = self.model(email=self.normalize_email(email), name=name)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, name=None):
        user = self.model(email=self.normalize_email(email), name=name)
        user.set_password(password)
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Basic user because we don't want Django's user class."""
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    def get_short_name(self):
        return self.email

    def get_full_name(self):
        return self.name

    @property
    def is_staff(self):
        return self.is_admin

    def pledge(self, amount, project, reward_tier=None):
        if project.created_by == self:
            raise BackingException('You can\'t back your own projects')
        if project in self.pledged_to.all():
            raise BackingException('You have already backed this project')
        if project.status != Project.STATUS_ACTIVE:
            raise BackingException('You can only back active projects')

        pledge = Pledge(project=project, user=self, amount=amount, chosen_reward_tier=reward_tier)
        pledge.save()
        return pledge

    def __str__(self):
        return self.name if self.name else self.email


class Project(models.Model):
    STATUS_ACTIVE = 0
    STATUS_SUCCESSFUL = 1
    STATUS_NOT_FUNDED = 2
    STATUS_CANCELED = 3
    STATUS_DRAFT = 4

    CURRENCY_USD = 0
    CURRENCY_EUR = 1
    CURRENCY_CAD = 2

    PROJECT_STATUS = [
        (STATUS_ACTIVE, 'ACTIVE'),
        (STATUS_SUCCESSFUL, 'SUCCESSFUL'),
        (STATUS_NOT_FUNDED, 'NOT_FUNDED'),
        (STATUS_CANCELED, 'CANCELED'),
        (STATUS_DRAFT, 'DRAFT'),
    ]

    CURRENCIES = [
        (CURRENCY_USD, '$'),
        (CURRENCY_EUR, '€'),
        (CURRENCY_CAD, 'CAD'),
    ]

    DEFAULT_DURATION = 60  # in days

    title = models.CharField(max_length=255)
    description = models.TextField()
    goal = models.FloatField(validators=[MinValueValidator(1)])
    cover_image = models.ImageField(null=True, blank=True)
    published_on = models.DateTimeField(null=True, blank=True)
    status = models.IntegerField(choices=PROJECT_STATUS, default=STATUS_DRAFT)
    currency = models.IntegerField(choices=CURRENCIES, default=CURRENCY_USD)
    created_by = models.ForeignKey('User', related_name='projects_created', on_delete=models.CASCADE)
    pledges = models.ManyToManyField('User', through='Pledge', related_name='pledged_to')

    @classmethod
    def from_db(cls, db, field_names, values):
        """
        Every time a project object is loaded from database, update its status.
        This is an expensive way of doing the status updates but considering
        this is a hobby project it shouldn't matter too much. I just wanted to avoid cron jobs and
        other convoluted asynchronous systems.
        """
        instance = super().from_db(db, field_names, values)
        instance.update_status()
        return instance

    @property
    def total_pledged_amount(self):
        return sum([pledge.amount for pledge in self.pledge_set.all()])

    @property
    def percentage_funded(self):
        return (self.total_pledged_amount / self.goal) * 100

    @property
    def is_draft(self):
        return self.status == Project.STATUS_DRAFT

    @property
    def finished_on(self):
        return self.published_on + datetime.timedelta(days=self.DEFAULT_DURATION)

    def publish(self):
        self.status = Project.STATUS_ACTIVE
        self.published_on = datetime.datetime.now(datetime.timezone.utc)

    def cancel(self):
        self.status = Project.STATUS_CANCELED

    def timedelta_remaining(self, relative_to=None):
        """
        :param relative_to: datetime.datetime
        :return: datetime.timedelta
        """
        if not relative_to:
            relative_to = datetime.datetime.now(datetime.timezone.utc)

        return self.finished_on - relative_to

    def update_status(self):
        # If the project is active and there's no time remaining
        if self.status == self.STATUS_ACTIVE and self.timedelta_remaining().total_seconds() <= 0:
            if self.total_pledged_amount >= self.goal:
                self.status = self.STATUS_SUCCESSFUL
            else:
                self.status = self.STATUS_NOT_FUNDED

    def __str__(self):
        return self.title


class Pledge(models.Model):
    amount = models.FloatField()
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    user = models.ForeignKey('User', related_name='pledges', on_delete=models.CASCADE)
    chosen_reward_tier = models.ForeignKey('RewardTier', related_name='pledges', on_delete=models.CASCADE, null=True, blank=True)


class RewardTier(models.Model):
    description = models.TextField()
    minimum_amount = models.FloatField()
    project = models.ForeignKey('Project', related_name='reward_tiers', on_delete=models.CASCADE)


class Comment(models.Model):
    text = models.TextField()
    project = models.ForeignKey('Project', related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey('User', related_name='comments')  # Don't delete comments on user deletion


class Update(models.Model):
    text = models.TextField()
    project = models.ForeignKey('Project', related_name='updates', on_delete=models.CASCADE)
    backers_only = models.BooleanField(default=False)

kickfarter/app/templates/app/project/edit.html
{% extends 'app/master.html' %}

{% block content %}
    {% load bootstrap3 %}
    <div class="container">
        <h1>Edit "{{ form.instance.title }}"</h1>

        <form action="{% url 'edit_project' form.instance.id %}" method="post" enctype="multipart/form-data" id="project-form">
            {% include 'app/snippets/project_form.html' with form=form %}

            {% csrf_token %}

            {% buttons %}
                <button type="submit" class="btn btn-default">Save changes</button>

                {% if form.instance.is_draft %}
                    <input type="hidden" name="publish" value="0" id="publish-input">
                    <button type="submit" class="btn btn-danger" id="publish-button">Publish</button>
                {% endif %}
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% if form.instance.is_draft %}
        <script>
            (function () {
                var $publishButton = document.getElementById('publish-button');
                var $form = document.getElementById('project-form');
                var $publishInput = document.getElementById('publish-input');

                $publishButton.addEventListener('click', function (event) {
                    event.preventDefault();
                    $publishInput.value = 1;
                    $form.submit();
                });
            })();
        </script>
    {% endif %}
{% endblock %}

kickfarter/app/templates/app/project/start.html
{% extends 'app/master.html' %}

{% block content %}
    {% load bootstrap3 %}
    <div class="container">
        <h1>Start a shitty project</h1>

        <form action="{% url 'start_project' %}" method="post" enctype="multipart/form-data">
            {% include 'app/snippets/project_form.html' with form=form %}

            {% csrf_token %}

            {% buttons %}
                <button type="submit" class="btn btn-default btn-lg">Start your project</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

kickfarter/app/templates/app/project/view.html
{% extends 'app/master.html' %}

{% block content %}
    {% load l10n %}
    <div class="container">
        {% if project.is_draft %}
            <div class="alert alert-warning">
                <strong>This project is a draft.</strong>
                You are viewing a project that has not been published yet. You can publish the project
                <a href="{% url 'edit_project' project.id %}">here</a>.
            </div>
        {% endif %}
        <header class="row header">
            <h3>{{ project.title }}</h3>
            <h5>by {{ project.created_by }}</h5>

            <div class="col-lg-8">

            </div>

            <div class="col-lg-4">
                <ul>
                    <li>{{ num_backers }} backers</li>
                    <li>{{ project.get_currency_display }}{% localize on %}{{ project.total_pledged_amount }}{% endlocalize %} pledged of {{ project.get_currency_display }}{% localize on %}{{ project.goal|floatformat:"0" }}{% endlocalize %}</li>
                    <li>TBI to go</li>
                </ul>
            </div>
        </header>

        <section class="row campaign">
            <div class="col-lg-8">
                <h4>About this project</h4>

                <p>
                    {{ project.description }}
                </p>

                <a href="{% url 'edit_project' project.id %}">Edit</a>
            </div>
            <div class="col-lg-4">
                <h4>Rewards</h4>
                {% for reward_tier in reward_tiers %}
                    <div class="reward-tier">
                        <h6>{{ project.get_currency_display }}{{ reward_tier.minimum_amount }}</h6>
                        <p>
                            {{ reward_tier.description }}
                        </p>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock %}